### ISSUE TITLE
Card component no longer present within standards documentation

### ISSUE THREAD

**Issue by MercatorSunday** [Royal-Navy/design-system#340] opened 2019-10-11 15:28 UTC
**Is your feature request related to a problem? Please describe.**
Card component no longer present within https://docs.royalnavy.io/components/. The Card component allowed me to provide information to users in a format that was (subjectively) a good match for my app.

**Describe the solution you'd like**
I wish the Card component to be re-included in the standards.

**Describe alternatives you've considered**
A 'rn-card' CSS element continues to exist within @royalnavy/css-framework so I could implement this within my app, however this might be nugatory work if it is not part of the new standard. Alternatively I could simply design my own method of displaying information from scratch, but would not wish to do so if a standard was going to be issued.  NB: If this component has been permanently deprecated, this would be useful to state explicitly within the standards.

**Additional context**
Screenshot of original feature below (data shown is illustrative only / mock):

![card_component](https://user-images.githubusercontent.com/56444093/66663850-5a180b80-ec43-11e9-8b66-28d8c215d4a9.png)

**Comment by antictor** [comment] 2019-10-11 19:55
There has been some updates made to the design. This needs to be finished so the CSS work can be done and a React component to match.

Design work is in progress and development on it will begin soon

**Comment by antictor** [comment] 2019-10-16 16:40
Duplicate of #345 

This will be started on soon.

**Closed as completed by antictor** 2019-10-16 16:40 UTC
Labels: Type: Enhancement
