### ISSUE TITLE
Change `render` function argument to be a prop bag in `Timeline`

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#1934] opened 2021-01-27 10:44 UTC
All subcomponents in `Timeline` have a `render` function which takes arguments but could be improved by the consumer by using a prop bag.

**Comment by m7kvqbe1** [comment] 2022-01-18 09:29
Closing as this is a duplicate of https://github.com/defencedigital/mod-uk-design-system/issues/1592.

**Closed as completed by m7kvqbe1** 2022-01-18 09:29 UTC
Labels: Type: Enhancement, Package: react-component-library, Release: Next major, Size: Small
