### ISSUE TITLE
Date picker start date locks in and can't be changed

### ISSUE THREAD

**Issue by bo7909** [Royal-Navy/design-system#1587] opened 2020-10-20 18:50 UTC
Locks in the start date once an initial start and end date has been selected meaning the end user cannot re-select a start date if they made an error initially.

https://www.npmjs.com/package/@royalnavy/react-component-library 

https://github.com/gpbl/react-day-picker

**Comment by m7kvqbe1** [comment] 2020-11-03 10:41
We have a feeling this might be a state management problem in the consuming app.

Please could you create a minimal reproduction.

**Comment by m7kvqbe1** [comment] 2020-11-04 11:07
I have been unable to create a reproduction (see working example below). 

The component appears to be functioning as intended.

I have closed this ticket for now - feel free to respond with more detail and we'll re-open it.

https://github.com/m7kvqbe1/tmp-repro-1/blob/master/src/pages/Home/Home.tsx

```typescript
import React, { useState } from 'react'
import {
  DatePicker,
  DATEPICKER_PLACEMENT,
} from '@royalnavy/react-component-library'

import { Main } from '../../layouts'

export const Home = () => {
  const [startDate, setStartDate] = useState(new Date(2018, 0, 11))

  function handleOnChange(e: any) {
    console.log(e)
    setStartDate(e.startDate)
  }

  return (
    <Main>
      <pre>{startDate.toString()}</pre>

      <DatePicker
        startDate={startDate}
        onChange={handleOnChange}
        placement={DATEPICKER_PLACEMENT.BELOW}
        isOpen
      />
    </Main>
  )
}
```

![2020-11-04 10 56 24](https://user-images.githubusercontent.com/48086589/98105388-d3f2e680-1e8f-11eb-925b-06a70f84476c.gif)

**Closed as completed by m7kvqbe1** 2020-11-04 11:07 UTC
Labels: Type: Bug
