### ISSUE TITLE
DatePicker aria-required-attr on .DayPicker-Caption

### ISSUE THREAD

**Issue by c9qsm62x** [Royal-Navy/design-system#2496] opened 2021-06-28 09:44 UTC
Hi 
We're getting an issue on our app using the day picker cause by react-day-picker. 

    Expected the HTML found at $('.DayPicker-Caption') to have no violations:

    <div class="DayPicker-Caption" role="heading"><div>September 2019</div></div>

    Received:

    "Required ARIA attributes must be provided (aria-required-attr)"

    Fix any of the following:
      Required ARIA attribute not present: aria-level

    You can find more information on this issue here: 
    https://dequeuniversity.com/rules/axe/3.3/aria-required-attr?application=axeAPI

I've notice that the error is coming from react-day-picker so I've made this issue to apply the fix when its resolved.
https://github.com/gpbl/react-day-picker/issues/922

**Comment by m7kvqbe1** [comment] 2021-07-05 18:10
This AXE error will no longer flag downstream due to the `FloatingBox` primitive being gracefully unmounted when hidden (this is in keeping with expected behaviour before a recent refactor).

It's worth noting that this ticket (in addition to https://github.com/Royal-Navy/design-system/issues/2496) shine a light on some surface area that needs additional test coverage. Hidden containers (or UI that requires interaction to render) has up to this point been missed by AXE (it is only aware of what is mounted in the DOM on initial render).

We have created a ticket to look into this (https://github.com/Royal-Navy/design-system/issues/2570) and closed this issue for now.

**Closed as completed by m7kvqbe1** 2021-07-05 18:10 UTC
Labels: Status: Blocked, Type: Bug, Size: Small
