### ISSUE TITLE
Alert component no longer present within standards documentation

### ISSUE THREAD

**Issue by MercatorSunday** [Royal-Navy/design-system#339] opened 2019-10-11 15:00 UTC
**Is your feature request related to a problem? Please describe.**
Alert component no longer present within https://docs.royalnavy.io/components/.  The alert component allowed me to provide feedback to users when validation failed (e.g. user leaving happy path).  For instance if a user searches for a NATO National Item Identification Number using less than mandatory 9 digits, the App would alert them that a malformed NIIN has been entered.

**Describe the solution you'd like**
I wish the Alert, or similar functionality, to be added to the standards.

**Describe alternatives you've considered**
An 'rn-alert' CSS element continues to exist within @royalnavy/css-framework so I could implement this within my app, however this might be nugatory work if it is not part of the new standard.  Alternatively a dialog or modal component could be used; content to do so if it is not intended to bring Alert back (NB: if that is the case then it would be useful for clarity to explicitly state when a component has been deprecated in favour of another within the standards).

**Additional context**
Screenshot of original feature below:
![alert_example](https://user-images.githubusercontent.com/56444093/66662126-225b9480-ec40-11e9-85cc-bee1d0a98609.png)

**Comment by antictor** [comment] 2019-10-16 16:40
This is a duplicate of #349 

This work will start soon

**Closed as completed by antictor** 2019-10-16 16:40 UTC
