### ISSUE TITLE
DatePicker shows invalid red boarder on valid input

### ISSUE THREAD

**Issue by c9qsm62x** [Royal-Navy/design-system#2355] opened 2021-05-12 14:10 UTC
Hi there is a red border applied to the DatePicker.

Steps to reproduce 
https://storybook.royalnavy.io/?path=/docs/date-picker--default
1. The input must be pristine 
2. Click and bring up the date picker modal
3. Choose a date 

![2021-05-12 15-08-22 2021-05-12 15_09_41](https://user-images.githubusercontent.com/75253719/117989363-28da5280-b334-11eb-813f-30134ee21a8f.gif)

version: 2.48.3

**Comment by m7kvqbe1** [comment] 2021-05-12 14:16
Closing as a duplicate of https://github.com/Royal-Navy/design-system/issues/2300.

Expect this to be resolved within the next couple of days.

**Closed as completed by m7kvqbe1** 2021-05-12 14:16 UTC
Labels: Type: Bug
